[package]
name = "tokio-tutorial"
description = "Working through the Tokio tutorial."
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
bytes = "1"
mini-redis = "0.4"
tokio.workspace = true
