[package]
name = "events-tasks"
description = "Combining events and long running tasks."
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
